from project import TerminalScribe
from drawshapes import Shape_Scribe, Line, Polygon, Circle

classes = {'TerminalScribe': TerminalScribe, 'Shape_Scribe': Shape_Scribe, 'Line': Line, 'Polygon': Polygon, 'Circle': Circle}

shape_scribes = {'Square': 
                [{'Attributes': {'position': [5, 5]}, 
                  'Movements': [{'func': Polygon.draw_poly_even, 'all args': [{'reps': None, 'args': {'sides': 4, 'length': 5, 'angle_offset': 0}}]},
                                {'func': Shape_Scribe.jump, 'all args': [{'reps': None, 'args': {'down': 7}}]}, 
                                {'func': Line.draw_line, 'all args': [{'reps': None, 'args': {'length': 4, 'angle': 90}}]},
                                {'func': Shape_Scribe.end_line, 'all args': None},
                               ]},
                               ],
           'Chevron': 
                [{'Attributes': {'position': [2, 2]}, 
                  'Movements': [{'func': TerminalScribe.start_new_line, 'all args': None},
                                {'func': TerminalScribe.forward, 'all args': [{'reps': 4, 'args': {'angle': 135}},
                                                                              {'reps': 4, 'args': {'angle': 45}},
                                                                             ]},
                                {'func': TerminalScribe.end_line, 'all args': None},
                                ]},
                 {'Attributes': {'position': [2, 3]}, 
                  'Movements': [{'func': TerminalScribe.start_new_line, 'all args': None},
                                {'func': TerminalScribe.forward, 'all args': [{'reps': 4, 'args': {'angle': 135}},
                                                                              {'reps': 4, 'args': {'angle': 45}},
                                                                             ]},
                                {'func': TerminalScribe.end_line, 'all args': None},
                               ]},
                                ],
           'Triskele':
                [{'Attributes': {'position': [10, 9], 'color_shift': True, 'framerate': 0.03,}, 
                  'Movements': [{'func': TerminalScribe.start_new_line, 'all args': None},
                                {'func': TerminalScribe.forward, 'all args': [{'reps': 4, 'args': {'angle': 90}},
                                                                             {'reps': 3, 'args': {'angle': 135}},
                                                                             {'reps': 3, 'args': {'angle': 180}},
                                                                             {'reps': 3, 'args': {'angle': 225}},
                                                                             {'reps': 2, 'args': {'angle': 270}},
                                                                             {'reps': 2, 'args': {'angle': 315}},
                                                                             {'reps': 2, 'args': {'angle': 0}},
                                                                             {'reps': 2, 'args': {'angle': 45}},
                                                                             {'reps': 1, 'args': {'angle': 90}}, 
                                                                             {'reps': 2, 'args': {'angle': 135}},
                                                                             {'reps': 2, 'args': {'angle': 225}},
                                                                             {'reps': 1, 'args': {'angle': 315}},
                                                                            ]},
                               {'func': TerminalScribe.end_line, 'all args': None},
                              ]},
                {'Attributes': {'position': [13, 8], 'color_shift': True}, 
                 'Movements': [{'func': TerminalScribe.start_new_line, 'all args': None},
                               {'func': TerminalScribe.forward, 'all args': [{'reps': 4, 'args': {'angle': 0}},
                                                                             {'reps': 3, 'args': {'angle': 45}},
                                                                             {'reps': 3, 'args': {'angle': 90}},
                                                                             {'reps': 3, 'args': {'angle': 135}},
                                                                             {'reps': 2, 'args': {'angle': 180}},
                                                                             {'reps': 2, 'args': {'angle': 225}},
                                                                             {'reps': 2, 'args': {'angle': 270}},
                                                                             {'reps': 2, 'args': {'angle': 315}},
                                                                             {'reps': 1, 'args': {'angle': 0}}, 
                                                                             {'reps': 2, 'args': {'angle': 45}},
                                                                             {'reps': 2, 'args': {'angle': 135}},
                                                                             {'reps': 1, 'args': {'angle': 225}},
                                                                             ]},
                               {'func': TerminalScribe.end_line, 'all args': None},
                              ]},
                {'Attributes': {'position': [12, 6], 'color_shift': True}, 
                 'Movements': [{'func': TerminalScribe.start_new_line, 'all args': None},
                               {'func': TerminalScribe.forward, 'all args': [{'reps': 4, 'args': {'angle': 225}},
                                                                             {'reps': 3, 'args': {'angle': 270}},
                                                                             {'reps': 3, 'args': {'angle': 315}},
                                                                             {'reps': 3, 'args': {'angle': 0}},
                                                                             {'reps': 2, 'args': {'angle': 45}},
                                                                             {'reps': 2, 'args': {'angle': 90}},
                                                                             {'reps': 2, 'args': {'angle': 135}},
                                                                             {'reps': 2, 'args': {'angle': 180}},
                                                                             {'reps': 1, 'args': {'angle': 225}}, 
                                                                             {'reps': 2, 'args': {'angle': 270}},
                                                                             {'reps': 2, 'args': {'angle': 0}},
                                                                             {'reps': 1, 'args': {'angle': 90}},
                                                                             ]},
                               {'func': TerminalScribe.end_line, 'all args': None},
                               ]},
                               ]
                               }